# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.2
script:
- set -o pipefail && xcodebuild test -workspace Example/TouchPresenter.xcworkspace -scheme TouchPresenter-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
